apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-mc-unsuported-runtime-ivjj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uxpv-tenant/mc-unsupported-runtime/devfile-sample-python-basic-rhtap-mc-unsuported-runtime-ivjj@sha256:c39821193745d2c639a5cce45af3fb13494d366bbb6be33fb962c3bcbf9634b8
        name: my-python
        resources: {}
status: {}
